local Specialty = warExtendedSpecialtyTraining

local careerImageNameLookUp =
{
  [1] =   "EA_Mastery_Ironbreaker1_d1.dds",
  [2] =   "EA_Mastery_Ironbreaker2_d1.dds",
  [3] =   "EA_Mastery_Ironbreaker3_d1.dds",
  [4] =   "EA_Mastery_Slayer1_d1.dds",
  [5] =   "EA_Mastery_Slayer2_d1.dds",
  [6] =   "EA_Mastery_Slayer3_d1.dds",
  [7] =   "EA_Mastery_RunePriest1_d1.dds",
  [8] =   "EA_Mastery_RunePriest2_d1.dds",
  [9] =   "EA_Mastery_RunePriest3_d1.dds",
  [10] =  "EA_Mastery_Engineer1_d1.dds",
  [11] =  "EA_Mastery_Engineer2_d1.dds",
  [12] =  "EA_Mastery_Engineer3_d1.dds",
  [13] =  "EA_Mastery_BlackOrc1_d1.dds",
  [14] =  "EA_Mastery_BlackOrc2_d1.dds",
  [15] =  "EA_Mastery_BlackOrc3_d1.dds",
  [16] =  "EA_Mastery_Choppa1_d1.dds",
  [17] =  "EA_Mastery_Choppa2_d1.dds",
  [18] =  "EA_Mastery_Choppa3_d1.dds",
  [19] =  "EA_Mastery_Shaman1_d1.dds",
  [20] =  "EA_Mastery_Shaman2_d1.dds",
  [21] =  "EA_Mastery_Shaman3_d1.dds",
  [22] =  "EA_Mastery_SquigHerder1_d1.dds",
  [23] =  "EA_Mastery_SquigHerder2_d1.dds",
  [24] =  "EA_Mastery_SquigHerder3_d1.dds",
  [25] =  "EA_Mastery_WitchHunter1_d1.dds",
  [26] =  "EA_Mastery_WitchHunter2_d1.dds",
  [27] =  "EA_Mastery_WitchHunter3_d1.dds",
  [28] =  "EA_Mastery_Knight1_d1.dds",
  [29] =  "EA_Mastery_Knight2_d1.dds",
  [30] =  "EA_Mastery_Knight3_d1.dds",
  [31] =  "EA_Mastery_BrightWiz1_d1.dds",
  [32] =  "EA_Mastery_BrightWiz2_d1.dds",
  [33] =  "EA_Mastery_BrightWiz3_d1.dds",
  [34] =  "EA_Mastery_WarriorPriest1_d1.dds",
  [35] =  "EA_Mastery_WarriorPriest2_d1.dds",
  [36] =  "EA_Mastery_WarriorPriest3_d1.dds",
  [37] =  "EA_Mastery_Chosen1_d1.dds",
  [38] =  "EA_Mastery_Chosen2_d1.dds",
  [39] =  "EA_Mastery_Chosen3_d1.dds",
  [40] =  "EA_Mastery_Marauder1_d1.dds",
  [41] =  "EA_Mastery_Marauder2_d1.dds",
  [42] =  "EA_Mastery_Marauder3_d1.dds",
  [43] =  "EA_Mastery_Zealot1_d1.dds",
  [44] =  "EA_Mastery_Zealot2_d1.dds",
  [45] =  "EA_Mastery_Zealot3_d1.dds",
  [46] =  "EA_Mastery_Magus1_d1.dds",
  [47] =  "EA_Mastery_Magus2_d1.dds",
  [48] =  "EA_Mastery_Magus3_d1.dds",
  [49] =  "EA_Mastery_Swordmaster1_d1.dds",
  [50] =  "EA_Mastery_Swordmaster2_d1.dds",
  [51] =  "EA_Mastery_Swordmaster3_d1.dds",
  [52] =  "EA_Mastery_ShadowWarrior1_d1.dds",
  [53] =  "EA_Mastery_ShadowWarrior2_d1.dds",
  [54] =  "EA_Mastery_ShadowWarrior3_d1.dds",
  [55] =  "EA_Mastery_WhiteLion1_d1.dds",
  [56] =  "EA_Mastery_WhiteLion2_d1.dds",
  [57] =  "EA_Mastery_WhiteLion3_d1.dds",
  [58] =  "EA_Mastery_Archmage1_d1.dds",
  [59] =  "EA_Mastery_Archmage2_d1.dds",
  [60] =  "EA_Mastery_Archmage3_d1.dds",
  [61] =  "EA_Mastery_BlackGuard1_d1.dds",
  [62] =  "EA_Mastery_BlackGuard2_d1.dds",
  [63] =  "EA_Mastery_BlackGuard3_d1.dds",
  [64] =  "EA_Mastery_WitchElf1_d1.dds",
  [65] =  "EA_Mastery_WitchElf2_d1.dds",
  [66] =  "EA_Mastery_WitchElf3_d1.dds",
  [67] =  "EA_Mastery_Disciple1_d1.dds",
  [68] =  "EA_Mastery_Disciple2_d1.dds",
  [69] =  "EA_Mastery_Disciple3_d1.dds",
  [70] =  "EA_Mastery_Sorceress1_d1.dds",
  [71] =  "EA_Mastery_Sorceress2_d1.dds",
  [72] =  "EA_Mastery_Sorceress3_d1.dds"
}

local pathName = "EA_InteractionWindow/Textures/"

function Specialty.SetMasteryImages()
  p("setting")
  SetCareerMasteryImages( pathName..careerImageNameLookUp[GameData.Player.SPECIALIZATION_PATH_1],
          pathName..careerImageNameLookUp[GameData.Player.SPECIALIZATION_PATH_2],
          pathName..careerImageNameLookUp[GameData.Player.SPECIALIZATION_PATH_3] )
end