--
-- NOTE: This file was auto-generated.
-- Contains all Func.xml message data exposed for use in Lua.
--
-- Not localized.
--

FuncXMLMessageData =
{
    { name = L"F_QUEST",         origin = L"client", description = L"Empty Description" },
    { name = L"F_UPDATE_SIEGE_LOOK_AT",  origin = L"both", description = L"The siege controller sends new theta/phi coords for the weapon and the server forwards the info to other clients in the detection list" },
    { name = L"F_PLAYER_EXIT",   origin = L"client", description = L"Empty Description" },
    { name = L"F_PLAYER_HEALTH",  origin = L"server", description = L"Multipurpose message containing current and maximum player health, action points, and morale" },
    { name = L"F_CHAT",          origin = L"both", description = L"Things are talking to each other" },
    { name = L"F_TEXT",          origin = L"both", description = L"String data for chat or alerts from the server" },
    { name = L"F_OBJECT_STATE",  origin = L"server", description = L"Tells client what to do with objects (monsters, players, statics)" },
    { name = L"F_OBJECT_DEATH",  origin = L"server", description = L"Something dies" },
    { name = L"F_PING",          origin = L"client", description = L"Empty Description" },
    { name = L"F_PLAYER_QUIT",   origin = L"server", description = L"The player is done with the game session" },
    { name = L"F_DUMP_STATICS",  origin = L"client", description = L"Unknown" },
    { name = L"F_HIT_PLAYER",    origin = L"server", description = L"Something takes damage" },
    { name = L"F_PLAYER_INFO",   origin = L"client", description = L"The client manually changed targets, or there was an LoS change" },
    { name = L"F_MAX_VELOCITY",  origin = L"server", description = L"Empty Description" },
    { name = L"F_SWITCH_REGION",  origin = L"server", description = L"Empty Description" },
    { name = L"F_PET_INFO",      origin = L"server", description = L"Tells the player about their pet" },
    { name = L"F_PLAYER_CLEAR_DEATH",  origin = L"server", description = L"The player wants to respawn?  Something like that..." },
    { name = L"F_COMMAND_CONTROLLED",  origin = L"client", description = L"The player wants to tell their pet to do something" },
    { name = L"F_GUILD_COMMAND",  origin = L"client", description = L"Empty Description" },
    { name = L"F_SURVEY_BEGIN",  origin = L"server", description = L"Empty Description" },
    { name = L"F_SHOW_DIALOG",   origin = L"server", description = L"The server wants the client to display a modal dialog" },
    { name = L"F_QUEST_INFO",    origin = L"server", description = L"Empty Description" },
    { name = L"F_INVITE_GROUP",  origin = L"client", description = L"Empty Description" },
    { name = L"F_JOIN_GROUP",    origin = L"client", description = L"Empty Description" },
    { name = L"F_PLAYER_DEATH",  origin = L"server", description = L"How the client should handle player death" },
    { name = L"F_GROUP_COMMAND",  origin = L"client", description = L"Empty Description" },
    { name = L"F_ZONEJUMP",      origin = L"client", description = L"Empty Description" },
    { name = L"F_PLAYER_EXPERIENCE",  origin = L"server", description = L"The player gains experience" },
    { name = L"F_PLAYER_STATS",  origin = L"server", description = L"Tells the player about its attributes (str, tough, etc...) as well as armor, tactic points (which are packed in a way that needs to get fixed), and dps. " },
    { name = L"F_MONSTER_STATS",  origin = L"server", description = L"Empty Description" },
    { name = L"F_PLAY_EFFECT",   origin = L"server", description = L"Empty Description" },
    { name = L"F_REMOVE_PLAYER",  origin = L"server", description = L"Empty Description" },
    { name = L"F_PLAYER_RENOWN",  origin = L"server", description = L"The player gains renown" },
    { name = L"F_MOUNT_UPDATE",  origin = L"server", description = L"An object is mounting or unmounting from another object" },
    { name = L"F_PLAYER_LEVEL_UP",  origin = L"server", description = L"Potentially temporary message informing the player about the details of their level increase" },
    { name = L"F_ANIMATION",     origin = L"server", description = L"Empty Description" },
    { name = L"F_PLAYER_WEALTH",  origin = L"server", description = L"The player gains or loses money" },
    { name = L"F_SET_TARGET",    origin = L"server", description = L"Tells the client about what other objects in the world are targeting.  Also used to force the player's target to a specific object" },
    { name = L"F_PLAY_SOUND",    origin = L"server", description = L"Tells the client to play a sound" },
    { name = L"F_PLAYER_STATE2",  origin = L"both", description = L"Inform the server about the current state of the player (position, LoS, flags, etc...)" },
    { name = L"F_KILLING_SPREE",  origin = L"server", description = L"You have advanced or timed out of your killing spree." },
    { name = L"F_CREATE_STATIC",  origin = L"server", description = L"The server informs the client about a static object that should be created" },
    { name = L"F_CREATE_MONSTER",  origin = L"server", description = L"The server informs the client about a monster that should be created" },
    { name = L"F_PLAYER_IMAGENUM",  origin = L"server", description = L"Empty Description" },
    { name = L"F_TRANSFER_ITEM",  origin = L"client", description = L"Client request to move an item to a different inventory block/slot" },
    { name = L"F_CRAFTING_STATUS",  origin = L"server", description = L"crafting status" },
    { name = L"F_SET_ABILITY_TIMER",  origin = L"server", description = L"Another multipurpose message.  Sets ability, pet-ability, global, layer-timer, and morale cooldowns" },
    { name = L"S_PONG",          origin = L"server", description = L"Empty Description" },
    { name = L"F_MAIL",          origin = L"both", description = L"Mail-related messaging." },
    { name = L"F_MORALE_LIST",   origin = L"server", description = L"Empty Description" },
    { name = L"F_SURVEY_ADDQUESTION",  origin = L"server", description = L"Empty Description" },
    { name = L"F_SURVEY_END",    origin = L"server", description = L"Empty Description" },
    { name = L"F_SURVEY_RESULT",  origin = L"client", description = L"Empty Description" },
    { name = L"F_EMOTE",         origin = L"both", description = L"Handles emote processing like waving and hugging...or more WAR-related emotes like bash, and chop." },
    { name = L"F_GFX_MOD",       origin = L"server", description = L"Updates the client with a new active GfxMod, so he can play the correct effect at button press." },
    { name = L"F_INSTANCE_INFO",  origin = L"server", description = L"Specifically for listing available instances for scenarios and city scenarios" },
    { name = L"F_KEEP_STATUS",   origin = L"server", description = L"To send keep data and guild banner data for the banners hanging around the keeps and the overhead map" },
    { name = L"F_PLAY_TIME_STATS",  origin = L"server", description = L"Personal play time stats" },
    { name = L"F_CATAPULT",      origin = L"server", description = L"Pushes the player to a different location" },
    { name = L"F_GRAVITY_UPDATE",  origin = L"server", description = L"An object has undergone a gravity change" },
    { name = L"F_REQUEST_LASTNAME",  origin = L"client", description = L"The player sends a desired LastName in preparation for setting it with a merchant" },
    { name = L"F_UPDATE_LASTNAME",  origin = L"server", description = L"A player's LastName has changed." },
    { name = L"F_CRASH_PACKET",  origin = L"client", description = L"Empty Description" },
    { name = L"F_START_SIEGE_MULTIUSER",  origin = L"both", description = L"The siege controller is initiating a multi-user firing mode to the server, or the server is bounching back the start firing mode to the other players." },
    { name = L"F_SIEGE_WEAPON_RESULTS",  origin = L"server", description = L"The siege has fired and here are the results." },
    { name = L"F_INTERACT_QUEUE",  origin = L"client", description = L"Empty Description" },
    { name = L"F_UPDATE_HOT_SPOT",  origin = L"server", description = L"Empty Description" },
    { name = L"F_GET_ITEM",      origin = L"server", description = L"Multipurpose message.  Mostly used for moving items around in the player inventory.  Also used for item enhancement." },
    { name = L"F_DUEL",          origin = L"server", description = L"Empty Description" },
    { name = L"F_PLAYER_JUMP",   origin = L"server", description = L"Teleports the player to a different location" },
    { name = L"F_MAGUS_DISC_UPDATE",  origin = L"server", description = L"A magus has changed his Disc of Tzeentch model" },
    { name = L"F_FIRE_SIEGE_WEAPON",  origin = L"client", description = L"A request from the client to fire a siege weapon" },
    { name = L"F_AUCTION_POST_ITEM",  origin = L"client", description = L"Post auction item" },
    { name = L"F_CAST_PLAYER_EFFECT",  origin = L"server", description = L"Usually results from ability usage.  Contains damage/healing information about an ability but most importantly, contains the effect information" },
    { name = L"F_AUCTION_SEARCH_QUERY",  origin = L"client", description = L"Query for searching auction items" },
    { name = L"F_SOCIAL_NETWORK",  origin = L"both", description = L"Empty Description" },
    { name = L"F_AUCTION_SEARCH_RESULT",  origin = L"server", description = L"Search result for auction items" },
    { name = L"F_AUCTION_BID_ITEM",  origin = L"client", description = L"Bid auction item" },
    { name = L"F_PLAYER_INVENTORY",  origin = L"server", description = L"Unknown...sends the entire inventory block to the player?" },
    { name = L"F_CHARACTER_INFO",  origin = L"server", description = L"Contains ability (add/remove) information, group information, and maybe one more thing.  This is a multipurpose message" },
    { name = L"F_INIT_STORE",    origin = L"server", description = L"Tells the player what they can buy from a store" },
    { name = L"F_STORE_BUY_BACK",  origin = L"server", description = L"Tells the player what items they sold that they can buy back" },
    { name = L"F_OBJECTIVE_INFO",  origin = L"server", description = L"Empty Description" },
    { name = L"F_OBJECTIVE_UPDATE",  origin = L"server", description = L"Empty Description" },
    { name = L"F_SCENARIO_INFO",  origin = L"server", description = L"Empty Description" },
    { name = L"F_SCENARIO_POINT_UPDATE",  origin = L"server", description = L"Empty Description" },
    { name = L"F_OBJECTIVE_STATE",  origin = L"server", description = L"Empty Description" },
    { name = L"F_REALM_BONUS",   origin = L"server", description = L"Empty Description" },
    { name = L"F_OBJECTIVE_CONTROL",  origin = L"server", description = L"Empty Description" },
    { name = L"F_INTERFACE_COMMAND",  origin = L"client", description = L"Multi-purpose message, used for far too many interface related commands to list them all here" },
    { name = L"F_SCENARIO_PLAYER_INFO",  origin = L"server", description = L"Empty Description" },
    { name = L"F_FLAG_OBJECT_STATE",  origin = L"server", description = L"Empty Description" },
    { name = L"F_FLAG_OBJECT_LOCATION",  origin = L"server", description = L"Empty Description" },
    { name = L"F_SALVAGE_ITEM",  origin = L"client", description = L"Salvage Item" },
    { name = L"F_AUCTION_BID_STATUS",  origin = L"server", description = L"Bid status of auction item" },
    { name = L"F_PUNKBUSTER",    origin = L"both", description = L"Relates to the PunkBuster anti-cheat system" },
    { name = L"F_ITEM_SET_DATA",  origin = L"server", description = L"Tells the client the details about an Item Set (a group of items that bestow synergistic bonuses when used together)" },
    { name = L"F_INTERACT",      origin = L"client", description = L"Empty Description" },
    { name = L"F_DO_ABILITY",    origin = L"client", description = L"A request from the client to fire an ability" },
    { name = L"F_SET_TIME",      origin = L"server", description = L"Empty Description" },
    { name = L"F_INIT_EFFECTS",  origin = L"server", description = L"Worst-named message ever.  Contains buff/debuff information about the player, its target, or group members." },
    { name = L"F_GROUP_STATUS",  origin = L"server", description = L"Empty Description" },
    { name = L"F_USE_ITEM",      origin = L"client", description = L"Player wants to use an item's ability (drink a health potion, etc...)" },
    { name = L"F_USE_ABILITY",   origin = L"server", description = L"Response to F_DO_ABILITY and F_DO_ABILITY_AT_POS.  Informs the client about what happened with their ability usage attempt" },
    { name = L"F_INFLUENCE_DETAILS",  origin = L"both", description = L"Empty Description" },
    { name = L"F_SWITCH_ATTACK_MODE",  origin = L"both", description = L"The player switches auto-attack state" },
    { name = L"F_BUG_REPORT",    origin = L"client", description = L"Empty Description" },
    { name = L"F_OBJECT_EFFECT_STATE",  origin = L"server", description = L"Also known as Client Effect State.  Sends down information about shaman waaagh, choppa berserk, etc..." },
    { name = L"F_EXPERIENCE_TABLE",  origin = L"server", description = L"Empty Description" },
    { name = L"F_CREATE_PLAYER",  origin = L"server", description = L"The server wants the client to create a player type game object" },
    { name = L"F_UPDATE_STATE",  origin = L"server", description = L"A variety of update types all with their own custom handlers" },
    { name = L"F_RVR_STATS",     origin = L"server", description = L"Personal RvR stats" },
    { name = L"F_CLIENT_DATA",   origin = L"both", description = L"Allows the client to save and retrieve its context-specific data block" },
    { name = L"F_INTERACT_RESPONSE",  origin = L"server", description = L"Empty Description" },
    { name = L"F_QUEST_LIST",    origin = L"server", description = L"Empty Description" },
    { name = L"F_QUEST_UPDATE",  origin = L"server", description = L"Empty Description" },
    { name = L"F_REQUEST_QUEST",  origin = L"client", description = L"Empty Description" },
    { name = L"F_QUEST_LIST_UPDATE",  origin = L"server", description = L"Empty Description" },
    { name = L"F_CAREER_CATEGORY",  origin = L"server", description = L"Empty Description" },
    { name = L"F_CAREER_PACKAGE_UPDATE",  origin = L"server", description = L"Empty Description" },
    { name = L"F_BUY_CAREER_PACKAGE",  origin = L"client", description = L"Empty Description" },
    { name = L"F_CAREER_PACKAGE_INFO",  origin = L"server", description = L"Empty Description" },
    { name = L"F_PLAYER_RANK_UPDATE",  origin = L"server", description = L"Some player levels up, this message only contains the level information required for playing the ding effect" },
    { name = L"F_DO_ABILITY_AT_POS",  origin = L"client", description = L"A request from the client to fire an ability at a position in the world" },
    { name = L"F_CHANNEL_LIST",  origin = L"server", description = L"Empty Description" },
    { name = L"F_TACTICS",       origin = L"both", description = L"Clears, swaps, adds, or removes active tactics (the ones the player has slotted)" },
    { name = L"F_TOK_ENTRY_UPDATE",  origin = L"server", description = L"Empty Description" },
    { name = L"F_TRADE_SKILL_UPDATE",  origin = L"server", description = L"packets for updating player's trade skill information" },
    { name = L"F_RENDER_PRIMITIVE",  origin = L"server", description = L"Leverages the devprims system so that server commands can draw objects on the client" },
    { name = L"F_INFLUENCE_UPDATE",  origin = L"server", description = L"Empty Description" },
    { name = L"F_INFLUENCE_INFO",  origin = L"server", description = L"Empty Description" },
    { name = L"F_KNOCKBACK",     origin = L"server", description = L"Pushes the player to a different location" },
    { name = L"F_PLAY_VOICE_OVER",  origin = L"server", description = L"Empty Description" },
    { name = L"F_INTERRUPT",     origin = L"client", description = L"The player wants to interrupt whatever it is he's doing" },
}
