--[[ <!-- <Window name="DevPadCopy" layer="overlay" movable="false" savesettings="false">
--                    <Size>
--                        <AbsPoint x="780" y="390"/>
--                    </Size>
--                    <Anchors>
--                        <Anchor point="topleft" relativePoint="topleft" relativeTo="DebugWindowBackground">
--                            <AbsPoint x="10" y="10"/>
--                        </Anchor>
--                        <Anchor point="topright" relativePoint="bottomright"
--                                relativeTo="DebugWindowLogDisplaySeperator">
--                            <AbsPoint x="-10" y="10"/>
--                        </Anchor>
--                    </Anchors>
--                    <EventHandlers>
--                        <EventHandler event="OnShown" function="warExtendedTerminal.OnShowCopy"/>
--                        <EventHandler event="OnHidden" function="warExtendedTerminal.OnHideCopy"/>
--                    </EventHandlers>
--                    <Windows>
--
--
--                        <EditBox name="$parentLog" inherits="EA_EditBox_NoFrame" maxchars="163840"
--                                 font="font_clear_small_bold"
--                                 scrollbar="CopyScrollBar" autoHideScrollBar="true" handleinput="true" alpha="0.97"
--                                 scrolling="vert">
--                            <Size>
--                                <AbsPoint x="780" y="390"/>
--                            </Size>
--                            <TextOffset x="0" y="2"/>
--                            <Anchors>
--                                <Anchor point="topleft" relativePoint="topleft" relativeTo="DebugWindowBackground">
--                                    <AbsPoint x="10" y="10"/>
--                                </Anchor>
--                                <Anchor point="bottomright" relativePoint="bottomright"
--                                        relativeTo="DebugWindowLogDisplaySeperator">
--                                    <AbsPoint x="-10" y="-10"/>
--                                </Anchor>
--                            </Anchors>
--                            <EventHandlers>
--                                <EventHandler event="OnTextChanged" function="warExtendedTerminal.PreventType"/>
--                                <EventHandler event="OnKeyTab" function="warExtendedTerminal.OnKeyTab"/>
--                            </EventHandlers>
--                            <Windows>
--                                <VerticalScrollbar name="CopyScrollBar" inherits="EA_ScrollBar_ChatVertical"
--                                                   layer="popup">
--                                    <Size>
--                                        <AbsPoint x="20" y="600"/>
--                                    </Size>
--                                    <Anchors>
--                                        <Anchor point="bottomright" relativePoint="bottomleft">
--                                            <AbsPoint x="-24" y="-0"/>
--                                        </Anchor>
--                                        <Anchor point="topright" relativePoint="topright"/>
--                                    </Anchors>
--                                </VerticalScrollbar>
--                            </Windows>
--                        </EditBox>
--                    </Windows>
--                </Window>-->]]---
